TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_TOKEN_KEY = ""
TWITTER_ACCESS_TOKEN_SECRET = ""

# Twitter Rate limiting use 15 minutes window
# <https://developer.twitter.com/en/docs/basics/rate-limiting>
BTZ_CHECK_INTERVAL_SECONDS = 60*15
BTZ_LAST_ROUND_NEWEST_FOLLOWER_ID_FILENAME = "last_round_newest_follower_id"
BTZ_BLOCKED_USERS_LOG_FILENAME = "blocked_users"
BTZ_CREATED_LATELY_DEFINITION_IN_DAYS = 7
BTZ_DEFAULT_PROFILE_IMAGE_ZOMBIE_STATUSES_COUNT_THRESHOLD = 0
BTZ_DEFAULT_PROFILE_IMAGE_ZOMBIE_FAVOURITES_COUNT_THRESHOLD = 0
BTZ_NON_DEFAULT_PROFILE_IMAGE_ZOMBIE_STATUSES_COUNT_THRESHOLD = 0
BTZ_NON_DEFAULT_PROFILE_IMAGE_ZOMBIE_FOLLOWERS_COUNT_THRESHOLD = 1
